version: "2.1"

services:
  sio-bdd:
    extends:
      file: sio-bdd/docker-compose.yml
      service: sio-bdd
  frontal-nginx:
    extends:
      file: frontal-nginx/docker-compose.yml
      service: frontal
  db:
    extends:
      file: mysql/docker-compose.yml
      service: db
  mailhog:
    extends:
      file: mailtrap/docker-compose.yml
      service: mailhog
  phpmyadmin:
    extends:
      file: mysql/docker-compose.yml
      service: phpmyadmin
  front:
    extends:
      file: front/docker-compose.yml
      service: front
