version: '3'
services:
  frontal:
    restart: unless-stopped
    image: nginx
    #network_mode: host
    ports:
      - 8080:80
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
