version: '3'
 
services:
  db:
    image: mariadb:10.4.24-focal 
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: btssio@49
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: unless-stopped
